# I like trailing commas in maps.  They let me insert new elements and
# see them as one line in a diff, not two.
TrailingComma:
  Enabled: false

# I use keyword arguments for a poor man's dependency injection to cut
# down on the magic in my tests.
ParameterLists:
  CountKeywordArgs: false

Encoding:
  Enabled: false

# If i'm using one function name and returning the contents of an
# attribute, that's OK.  The alternative would be this, which I find
# confusing and often not really what I mean:
#
# attr_reader :something_else
# alias_method :something, :something_else
TrivialAccessors:
   ExactNameMatch: true

#
# Add 'X XX' to the standard list
#
Style/CommentAnnotation:
   Keywords:
    - "TOD\
       O"
    - "FIXM\
       E"
    - "OPTIMIZ\
      E"
    - "HAC\
      K"
    - "REVIE\
       W"
    - "XX\
       X"
