language: ruby
cache: bundler
# without --debug, JRuby doesn't support coverage reporting
before_install:
  # https://bundler.io/blog/2019/05/14/
  #   solutions-for-cant-find-gem-bundler-with-executable-bundle.html
  - gem update --system
  - gem install bundler
env:
  - JRUBY_OPTS="--debug"
rvm:
  # - ruby-head # excess warning logging
  - 2.5
  - 2.6
  - 2.7
#  - jruby-head # linguist gem doesn't support JRuby; bundle install doesn't work.
