version: 2
jobs:
  build:
    working_directory: ~/quality
    docker:
      - image: apiology/circleci-ruby:latest
    environment:
      BUNDLE_PATH: '/home/circleci/vendor/bundle'
    steps:
      - checkout
      - type: cache-restore
        key: quality-v2-{{ checksum "quality.gemspec" }}-{{ checksum "Gemfile" }}
      - run: bundle install --jobs=4
      - type: cache-save
        key: quality-v2-{{ checksum "quality.gemspec" }}-{{ checksum "Gemfile" }}
        paths:
          - "/home/circleci/vendor/bundle"
      - run: bundle exec rake --jobs=4 ci
      - run:
          command: bundle exec rake after_test_success
          filters:
            branches:
              only: master
