version: 2
jobs:
  build:
    working_directory: ~/quality
    docker:
      - image: apiology/circleci-ruby:latest
    steps:
      - checkout
      - type: cache-restore
        key: quality-{{ checksum "quality.gemspec" }}-{{ checksum "Gemfile" }}
      - run: "env | grep bundle"
      - run: bundle config set path 'vendor/bundle'
      - run: bundle install --jobs=4
      - run: bundle exec rake --jobs=4 ci
      - run:
          command: bundle exec rake after_test_success
          filters:
            branches:
              only: master
      - type: cache-save
        key: quality-{{ checksum "quality.gemspec" }}-{{ checksum "Gemfile" }}
        paths:
          - "vendor/bundle"
